export const SKIPPABLE_KEYS = [
  'email',
  'id',
  'Lead_Source_Detail__c',
  'utm_source__c',
  'utm_medium__c',
  'utm_campaign__c',
  'mcUserId__c',
  'city',
  'Region__c',
  'First_Lead_Source__c',
  'First_Lead_Source_Category__c',
  'First_Lead_Source_Detail__c',
  'First_Touch_Detail__c',
  'Last_LeadSource__c',
  'Last_LeadSourceCategory__c',
  'Last_MKT_UTM_Campaign__c',
  'Last_MTA__c',
  'Lead_Source_Category__c',
  'leadSource',
  'marketingSuspendedReason',
  'originalSearchEngine',
  'originalSourceInfo',
  'originalSourceType',
  'Total_MTA_Count_CGA__c',
  'Total_MTA_Count_CrimsonCore__c',
];

export const PRIORITY_FIELD_MAP = {
  country: ['Contact', 'Lead'],
  leadSource: [
    'Advertising',
    'Paid Search',
    'Organic',
    'Marketing Generated',
    'Event',
    'Tradeshow',
    'Content',
    'Webinar',
    'Referral',
    'Sales Generated',
    'Direct',
  ],
  leadStatus: [
    'Qualified',
    'Disqualified',
    'IC Complete',
    'IC Booked',
    'Initial Contact Made',
    'Attempting Contact',
    'New (Not Contacted)',
    'Change to Sales Lead',
    'Nurturing',
    'Future Potential',
    'Migrated',
  ],
  Division__c_account: [
    'Crimson',
    'CGA',
    'Medview',
    'Medview Ecommerce',
    'Crimson Athletic',
    'Partnerships',
    'Tutoring',
    'Tutoring Ecommerce',
    'Crimson Rise',
    'Crimson Careers',
    'CRI',
    'Postgraduate',
    'Tours',
    'Transfer',
    'Boarding/Day School',
    'Dux College',
  ],
  Division__c: [
    'Crimson',
    'CGA',
    'Medview',
    'Medview Ecommerce',
    'Crimson Athletic',
    'Partnerships',
    'Tutoring',
    'Tutoring Ecommerce',
    'Crimson Rise',
    'Crimson Careers',
    'CRI',
    'Postgraduate',
    'Tours',
    'Transfer',
    'Boarding/Day School',
    'Dux College',
  ],
  CGA_Core_Split__c: ['Contact', 'Lead'],
  Region_Mapping__c: ['Contact', 'Lead'],
  sfdcType: ['Contact', 'Lead'],
};
